### ISSUE TITLE
When setting "prometheusSupport: true" on a cluster without Prometheus installed, the operator (v2.3.0) segfaults

### ISSUE THREAD

**Issue by jgoeres** [instaclustr/cassandra-operator#338]
Hi,

when enabling prometheus support by setting

    prometheusSupport: true

on a CassandraDataCenter and applying it on a cluster without Prometheus operator, the Cassandra operator segfaults:

    $ kubectl logs cassandra-operator-6b748dcc69-tmc29
    {"level":"info","ts":1580808639.3200963,"logger":"cmd","msg":"Version: v2.3.0"}
    {"level":"info","ts":1580808639.3201246,"logger":"cmd","msg":"Go Version: go1.13.5"}
    {"level":"info","ts":1580808639.320134,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
    {"level":"info","ts":1580808639.3201413,"logger":"cmd","msg":"Version of operator-sdk: v0.10.0"}
    {"level":"info","ts":1580808639.320342,"logger":"leader","msg":"Trying to become the leader."}
    {"level":"info","ts":1580808639.7061956,"logger":"leader","msg":"Found existing lock with my name. I was likely restarted."}
    {"level":"info","ts":1580808639.7062466,"logger":"leader","msg":"Continuing as the leader."}
    {"level":"info","ts":1580808639.9692411,"logger":"cmd","msg":"Registering Components."}
    {"level":"info","ts":1580808639.9700491,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"cassandrabackup-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1580808639.970593,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"cassandrabackup-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1580808639.970912,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"cassandradatacenter-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1580808639.9713807,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"cassandradatacenter-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1580808639.9717276,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"cassandradatacenter-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1580808641.3433983,"logger":"cmd","msg":"Could not create ServiceMonitor object","error":"no ServiceMonitor registered with the API"}
    {"level":"info","ts":1580808641.3434381,"logger":"cmd","msg":"Install prometheus-operator in your cluster to create ServiceMonitor objects","error":"no ServiceMonitor registered with the API"}
    {"level":"info","ts":1580808641.343452,"logger":"cmd","msg":"Starting the Cmd."}
    {"level":"info","ts":1580808641.851747,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"cassandradatacenter-controller"}
    {"level":"info","ts":1580808641.8518426,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"cassandrabackup-controller"}
    {"level":"info","ts":1580808641.9972413,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"cassandrabackup-controller","worker count":1}
    {"level":"info","ts":1580808641.997312,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"cassandradatacenter-controller","worker count":1}
    {"level":"info","ts":1580808641.997385,"logger":"controller_cassandradatacenter","msg":"Reconciling CassandraDataCenter","Request.Namespace":"yukon","Request.Name":"yukon-cassandra"}
    E0204 09:30:42.388070       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
    /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/runtime/runtime.go:76
    /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/runtime/runtime.go:65
    /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/runtime/runtime.go:51
    /usr/local/go/src/runtime/panic.go:679
    /usr/local/go/src/runtime/panic.go:199
    /usr/local/go/src/runtime/signal_unix.go:394
    /code/pkg/controller/cassandradatacenter/metadata.go:69
    /code/pkg/controller/cassandradatacenter/services.go:20
    /code/pkg/controller/cassandradatacenter/services.go:149
    /code/pkg/controller/cassandradatacenter/cassandradatacenter_controller.go:189
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:215
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:158
    /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:133
    /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:134
    /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:88
    /usr/local/go/src/runtime/asm_amd64.s:1357
    panic: runtime error: invalid memory address or nil pointer dereference [recovered]
            panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1266907]
    
    goroutine 902 [running]:
    k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
            /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/runtime/runtime.go:58 +0x105
    panic(0x13e51c0, 0x2207180)
            /usr/local/go/src/runtime/panic.go:679 +0x1b2
    github.com/instaclustr/cassandra-operator/pkg/controller/cassandradatacenter.PrometheusLabels(0xc0005ca900, 0xc001026200)
            /code/pkg/controller/cassandradatacenter/metadata.go:69 +0x107
    github.com/instaclustr/cassandra-operator/pkg/controller/cassandradatacenter.createOrUpdatePrometheusService(0xc000222aa0, 0x0, 0x0, 0x0)
            /code/pkg/controller/cassandradatacenter/services.go:20 +0x11b
    github.com/instaclustr/cassandra-operator/pkg/controller/cassandradatacenter.createOrUpdatePrometheusServiceMonitor(0xc000222aa0, 0xc000c4f0e0, 0xc00101a000)
            /code/pkg/controller/cassandradatacenter/services.go:149 +0x61
    github.com/instaclustr/cassandra-operator/pkg/controller/cassandradatacenter.(*ReconcileCassandraDataCenter).Reconcile(0xc000429380, 0xc000a7f3e9, 0x5, 0xc000a7f430, 0xf, 0xc000d26e60, 0x6, 0xc000604c80, 0x12)
            /code/pkg/controller/cassandradatacenter/cassandradatacenter_controller.go:189 +0x872
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000222140, 0xc000447b00)
            /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:215 +0x20a
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
            /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:158 +0x36
    k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000d23650)
            /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:133 +0x5e
    k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000d23650, 0x3b9aca00, 0x0, 0xc000545601, 0xc00009ed20)
            /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:134 +0xf8
    k8s.io/apimachinery/pkg/util/wait.Until(0xc000d23650, 0x3b9aca00, 0xc00009ed20)
            /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628/pkg/util/wait/wait.go:88 +0x4d
    created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
            /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:157 +0x32e
    

Regards

J

**Comment by smiklosovic** [comment]
hi @jgoeres, thank you, I ll take a look. I think I saw this already and I fixed it but I ll double check and let you know.

**Comment by smiklosovic** [comment]
@jgoeres this should be fixed in v3.1.1, can you pull it and try it out? (all images should have tag v3.1.1, cassandra image was renamed and is "cassandra-3.11.5:v3.1.1", notice "3.11.5" is part of image name itself

**Comment by jgoeres** [comment]
Hi,

thanks for looking into this. Not sure why I had been using such an ancient image... I think I was following along the "Getting started" guide (which IIRC referred to "latest") and then somehow confirmed that latest was 2.3.0.
Anyway, it still happens in 3.1.1:

    $ kubectl logs test-cassandra-operator-69bf56df6c-k8dn7
    {"level":"info","ts":1580887938.1688473,"logger":"cmd","msg":"Version: v3.1.1"}
    {"level":"info","ts":1580887938.1688688,"logger":"cmd","msg":"Go Version: go1.13.6"}
    {"level":"info","ts":1580887938.1689677,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
    {"level":"info","ts":1580887938.1691637,"logger":"cmd","msg":"Version of operator-sdk: v0.11.0"}
    {"level":"info","ts":1580887938.169339,"logger":"leader","msg":"Trying to become the leader."}
    {"level":"info","ts":1580887939.0759797,"logger":"leader","msg":"Found existing lock with my name. I was likely restarted."}
    {"level":"info","ts":1580887939.0760193,"logger":"leader","msg":"Continuing as the leader."}
    {"level":"info","ts":1580887939.633309,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"0.0.0.0:8383"}
    {"level":"info","ts":1580887939.6335692,"logger":"cmd","msg":"Registering Components."}
    {"level":"info","ts":1580887939.6338594,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"cassandrabackup-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1580887939.6339645,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"cassandrabackup-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1580887939.6341372,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"cassandradatacenter-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1580887939.6342213,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"cassandradatacenter-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1580887939.6342852,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"cassandradatacenter-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1580887941.8821156,"logger":"metrics","msg":"Metrics Service object updated","Service.Name":"cassandra-operator-metrics","Service.Namespace":"test"}
    {"level":"info","ts":1580887942.434754,"logger":"cmd","msg":"Could not create ServiceMonitor object","error":"no ServiceMonitor registered with the API"}
    {"level":"info","ts":1580887942.4347906,"logger":"cmd","msg":"Install prometheus-operator in your cluster to create ServiceMonitor objects","error":"no ServiceMonitor registered with the API"}
    {"level":"info","ts":1580887942.434805,"logger":"cmd","msg":"Starting the Cmd."}
    {"level":"info","ts":1580887942.4357333,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
    {"level":"info","ts":1580887942.5366464,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"cassandrabackup-controller"}
    {"level":"info","ts":1580887942.5368502,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"cassandradatacenter-controller"}
    {"level":"info","ts":1580887942.6377313,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"cassandradatacenter-controller","worker count":1}
    {"level":"info","ts":1580887942.6379812,"logger":"controller_cassandradatacenter","msg":"Reconciling CassandraDataCenter","Request.Namespace":"test","Request.Name":"test-cassandra"}
    {"level":"info","ts":1580887942.6377625,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"cassandrabackup-controller","worker count":1}
    E0205 07:32:22.753544       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
    /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/runtime/runtime.go:76
    /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/runtime/runtime.go:65
    /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/runtime/runtime.go:51
    /usr/local/go/src/runtime/panic.go:679
    /usr/local/go/src/runtime/panic.go:199
    /usr/local/go/src/runtime/signal_unix.go:394
    /code/pkg/controller/cassandradatacenter/metadata.go:69
    /code/pkg/controller/cassandradatacenter/services.go:19
    /code/pkg/controller/cassandradatacenter/services.go:148
    /code/pkg/controller/cassandradatacenter/cassandradatacenter_controller.go:188
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:216
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:192
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:171
    /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152
    /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153
    /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88
    /usr/local/go/src/runtime/asm_amd64.s:1357
    panic: runtime error: invalid memory address or nil pointer dereference [recovered]
            panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12c7307]
    
    goroutine 1054 [running]:
    k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
            /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/runtime/runtime.go:58 +0x105
    panic(0x144d620, 0x22d3370)
            /usr/local/go/src/runtime/panic.go:679 +0x1b2
    github.com/instaclustr/cassandra-operator/pkg/controller/cassandradatacenter.PrometheusLabels(0xc000a82000, 0xc000214200)
            /code/pkg/controller/cassandradatacenter/metadata.go:69 +0x107
    github.com/instaclustr/cassandra-operator/pkg/controller/cassandradatacenter.createOrUpdatePrometheusService(0xc000838320, 0x0, 0xc00043c000, 0x0)
            /code/pkg/controller/cassandradatacenter/services.go:19 +0x102
    github.com/instaclustr/cassandra-operator/pkg/controller/cassandradatacenter.createOrUpdatePrometheusServiceMonitor(0xc000838320, 0xc000934200, 0xc00018a000)
            /code/pkg/controller/cassandradatacenter/services.go:148 +0x69
    github.com/instaclustr/cassandra-operator/pkg/controller/cassandradatacenter.(*ReconcileCassandraDataCenter).Reconcile(0xc000795350, 0xc0008c8709, 0x5, 0xc0008c8750, 0xf, 0xc00032dcd8, 0xc0002b4360, 0xc0002b41b8, 0x1829080)
            /code/pkg/controller/cassandradatacenter/cassandradatacenter_controller.go:188 +0x869
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000578820, 0x14ab8e0, 0xc0003746c0, 0x43eb00)
            /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:216 +0x162
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000578820, 0x430200)
            /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:192 +0xcb
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000578820)
            /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:171 +0x2b
    k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0003904e0)
            /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152 +0x5e
    k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0003904e0, 0x3b9aca00, 0x0, 0x1, 0xc00061cea0)
            /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153 +0xf8
    k8s.io/apimachinery/pkg/util/wait.Until(0xc0003904e0, 0x3b9aca00, 0xc00061cea0)
            /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88 +0x4d
    created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
            /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:157 +0x32e

**Comment by smiklosovic** [comment]
@jgoeres 
I think it boils down to the fact that you have not set labels on operator. It fails on the part of the code where labels are applied and I am not completely sure why as I hit this problem before and fixed it.

Please try to annotate your prometheus service like it is described here:

https://github.com/instaclustr/cassandra-operator/blob/master/doc/custom-configuration.md#custom-labels-for-created-objects

Why do you try to have prometheus support set to true when you know you do not have prometheus? (but I agree that this should be fixed but it is unrelated to "having prometheus or not")

**Comment by smiklosovic** [comment]
@jgoeres you are right I fixed that. :) I ll release new images and I ll close this afterwards. Thanks.

**Comment by smiklosovic** [comment]
https://github.com/instaclustr/cassandra-operator/pull/340

**Comment by jgoeres** [comment]
Thank you. It is of course no big deal, once I figured out what caused the crash, I just disabled prometheus support (I saw the error message "Could not create ServiceMonitor", but at first didn't think it was related. ).
Why I had prometheus support enabled in the first place?
Well, I am working on a Helm chart for deploying a product that makes use of the cassandra operator, and since it only watches one namespace, I deploy it as part of the product install. I have a global switch in my chart that enables prometheus support for all our images, which is enabled by default. I wired that same switch to also enable/disable prometheus support for the operator. I do my testing on minikube, where I don't have prometheus deployed since I am slightly RAM constrained, that's how I ran into the issue.

**Comment by smiklosovic** [comment]
I see, well, you can have _cluster scoped operator_, which means that operator is deployed in one namespaces but clusters are running in a different one, please follow these docs:

https://github.com/operator-framework/operator-sdk/blob/master/doc/operator-scope.md#cluster-scoped-operator-usage

**Comment by smiklosovic** [comment]
@jgoeres grab the `latest` or `v3.2.0`.

**Comment by jgoeres** [comment]
Works fine with 3.2.0, thank you!
